### ISSUE TITLE
Support for LDAP protocol version

### ISSUE THREAD

**Issue by josefsabl** [foglcz/ldap-authenticator#8]
LDAP in its defaul configuration has problems with non UTF8 encodings and diacritics. It can be configured by using.

`ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, 3);`

But there is no obvious way how to configure this it this authenticator.

**Comment by foglcz** [comment]
:+1: 

Thanks for catching this!

**Comment by josefsabl** [comment]
Today we encountered another problem related to this. The version of protocol obviously doesn't affect only diacritics. We ran into the problem where on specific system it was impossible to connect to LDAP server at all. The problem was solved by setting protocol version to 3. As noted here.

http://stackoverflow.com/questions/7720795/php-5-3-5-ldap-search-search-cant-contact-ldap-server

**Comment by josefsabl** [comment]
And now I realized that it in fact is supported, only not documented. You can specify it in config.neon as:

```
ldap:
    hostname: 
    port: 
    baseDn: 
    domain:
    loadGroups: true
    options:
        17: 3                   # 17 == LDAP_OPT_PROTOCOL_VERSION const
```
